center-for-threat-informed-defense/tram

src/tram/tram/ml/base.py
src/tram/tram/models.py
tests/tram/test_base.py

This change is to simplify how training data is retrieved from the database so that future improvements are easier. I ran this locally and the application behaved as expected. For manual testing, I trained a model and uploaded reports.
What changed:
- get_training_data now returns an X, y tuple instead of objects. The X, y tuple has better ergonomics for the SKLearn pipeline
- test() and train() both call get_training_data() directly
- Removed dead code (y_counts) in SKLearnModel.test
- Deleted SKLearnModel._load_and_vectorize_data. It has been replaced by the improved get_training_data().
- Replaced _preprocess_text() with lemmatize().
- Input changed from a list of sentences to a single sentence
- Output changed from a list of lemmatized sentences to a single lemmatized sentence …

Refactor get_training_data for simplicity

---

.dockerignore
.github/workflows/build-push-container.yml
.github/workflows/linter.yml
.gitignore
.hadolint.yaml
.pre-commit-config.yaml
CONTRIBUTING.md
Dockerfile
Makefile
README.md
docker/docker-compose.yml
docker/entrypoint.sh
pyproject.toml
requirements/requirements.txt
requirements/test-requirements.txt
tox.ini

PR adds some automation and shortcuts to simplify common developer/user usage scenarios and best practices.
* Release Process
* When a release on the github repository is created, the container will automatically be built and pushed to the Github Container Registry with the version set to the tag, in addition to a `latest` tag.
* Linting
* Adds automatic linting locally (via pre-commit), in CI (via super-linter). 
* Adds pre-commit configuration for local running of standard linting tasks (see .pre-commit-config.yaml for details)
* CI will report on each individual linter separately to easily identify any linting failures (Dockerfiles, shell scripts, python, etc.)
* Makefile
* Adds Makefile to simplify/standardize setup, build, and usage of product
* Targets for the following
* container …

refactor(ci, build): Simplify build process and developer workflow for running tests and container builds

---

requirements/test-requirements.txt

The new major release of `pytest` causing problems, this PR restricts pytest version to use on the build.

CI-Build Fix

---

Dockerfile
Makefile
requirements/requirements.txt
tox.ini

* bump nltk to 3.6.7
* added explicit download for omw-1.4 corpus in tox
* added explicit download for omw-1.4 corpus in docker container
* tweaks to clean targets in makefile to clean up after test run with clean-all target
closes #134

fix(build): bump nltk from 3.6.5 -> 3.6.7, nltk requires explicit download of omw corpus

---

src/tram/tram/views.py

- Attack technique was not changed to attack object, breaks that tab.
This commit was cherry-picked [4e15c10](https://github.com/center-for-threat-informed-defense/tram/pull/129/commits/4e15c102b174c9b5d36d1df6800934e98e680ff7) from @bsnyder70. It had to be merge-conflicted in order to push it in.
closes #126

[CTID-14] Fixed Sentence Display

---

README.md

- Add missing instructions for developers, or  users running directly on host. The README.md does not say you needed to train your model first triggering the `LogisticRegression` error.
closes #130

[CTID-13] Add missing instructions

---

docker/entrypoint.sh

- The pipeline process when specified without the `--run-forever` flag will die out immediately if there are no jobs to process or when the jobs are finished processing. This causes any jobs submitted using Docker to stay in `Queued` state for ever and are only processed when restarted.
New docker images will be needed for the update to address users that make use of the published images.
closes #131
closes #114

Fix Docker ML pipeline

---

Dockerfile

- add docker example to define proxy settings and adding certs to the docker build
The user would not be using the image itself, instead would be cloning the repo and making the build locally and uncommenting the necessary lines. It should be transparent if using docker-compose by replacing `image:` section with:
```yml
version: '3.5'
services:
tram:
build:
context: .
dockerfile: Dockerfile
```
To build it using the local Dockerfile configuration.
closes #95

[CTID-17] Docker Documentation

---

src/scripts/reformat_training_data.py
src/tram/tram/management/commands/attackdata.py
src/tram/tram/management/commands/pipeline.py
src/tram/tram/ml/base.py
src/tram/tram/settings.py

While getting familiar with the project, I noticed there are a lot of print() and sys.stdout.write() scattered throughout the code. This PR sets up logging using the standard Django approach.
Before:
```
$ python src/tram/manage.py pipeline run
LogisticRegressionModel loaded from /Volumes/Code/ctid/tram/data/ml-models/LogisticRegressionModel.pkl
Running ML Pipeline with Model: logreg
Processing Job #18: lorem_4bGyFhK.pdf
Created report Report for lorem_4bGyFhK.pdf
```
After:
```
$ python src/tram/manage.py pipeline run
[2022-02-11 18:49:18] INFO [tram.ml.base] LogisticRegressionModel loaded from /Volumes/Code/ctid/tram/data/ml-models/LogisticRegressionModel.pkl
[2022-02-11 18:49:18] INFO [tram.management.commands.pipeline] Running ML Pipeline with Model: logreg
[2022-02-11 18:49:18] INFO …
```

refactor(logs): Set up Django logging to replace existing print()'s

---

.coveragerc
.gitignore
src/tram/tram/settings.py
tox.ini

During development, every time you save a source file it reloads the
Django server which generates a new SECRET_KEY which means you have to
log in again, which is extremely tedious. This commit saves the
generated key to the data directory so that it can be reused.
Also modified code coverage to exclude `settings.py` and migrations.

refactor(auth): Persist the SECRET_KEY

---

src/tram/tram/report/docx.py
src/tram/tram/templates/index.html
src/tram/tram/views.py
tests/tram/report/test_docx.py
tests/tram/test_views.py

Cherry picked from @bsnyder70's PR #129 to merge with linted code.
closes #99
closes #26

feat(export): Add .docx export

---

README.md
src/tram/management/commands/attackdata.py
src/tram/ml/base.py
src/tram/static/js/analyze.js
src/tram/static/js/base.js
src/tram/static/js/technique-sentences.js
src/tram/templates/base.html
src/tram/templates/index.html
src/tram/templates/technique_sentences.html
src/tram/templates/tram_documentation.html
src/tram/views.py

General findings from SonarCloud 
- They relate to unused variables, best practices, and code quality.
- Update README, you can't use `tram runserver` without setting the DEBUG flag.

SonarCloud findings

---

src/tram/templates/base.html

- Adds text to the existing upload button to help emphasize the tool options. Did not remove the icon.
closes #106

[CTID-28] Add "Upload Report" button

---

src/tram/templates/analyze.html
src/tram/templates/base.html

- Enclose the link used to go back to the index page inside a block (opposed to using JS to update the element on the client side)
- The block will be used to modify its content on the analyze page to provide a button with more relevant text.
There are a few UX changes that could be made based on recommendation on this PR:
- Use different text like "Save & Close", "Close", "Close Report", "Save Report", "Back", others?
- Use different classes to change the look like be button be solid, outline with different color, particular color of interest (red?)
closes #92

[CTID-29] Add a "Close Button" on the Analyze Page

---

Dockerfile
Makefile
README.md

- Provide detailed steps for how to move Docker images across an airgap.
- The rest of the installation is the same.
- Also refactor the way we build certs into the Docker image. The old approach
required editing the dockerfile, which led certain people (<cough> me) to
accidentally check in the Dockerfile with their own issuer cert configured in
it. The new approach passes the information in the environment.
closes #104

docs(README): Add instructions for airgap deployment (fixes #104)

---

src/tram/views.py
tests/conftest.py
tests/tram/test_views.py

This pull requests adds an endpoint for fetching reports created for certain documents. 
> Closes #166.
- Document ID and Job ID is returned in headers from `upload` method.
- This way, users accessing TRAM not via GUI can track the progress of the jobs created for their uploaded documents.
- *They can also get all the reports created for these documents.*
> `/api/report-export/?doc-id=<DOC_ID>`

Adds endpoint for fetching reports by using document IDs.

---

README.md
docker/docker-compose.yml
src/tram/admin.py
src/tram/settings.py

Not sure why these fields were marked as readonly, but it prevents any meaningful usage of the AttackObject admin UI. Opening this PR as a draft so I can get some feedback on whether this breaks anything else. (Fixes #163)

Enable creation of AttackObject in Django admin

---

.pre-commit-config.yaml
README.md
requirements/requirements.txt
src/tram/settings.py
src/tram/urls.py
src/tram/views.py
tests/tram/test_views.py

Add an API route to trigger training of a model. This runs synchronously and the current implementation is a stop gap until a point in time where we could have training run asynchronously (e.g. background workers reading a message queue). 
Adapted from @bsnyder70's PR #129. Unlike the PR, this implementation does not have a GUI component because the synchronous aspect of the API call would lead to high latency in the GUI (e.g. click the button and it freezes for 10-15 seconds while it trains the model). For now training can only be triggered from an API call (or from the command line, which has not changed in this PR).
TRAM doesn't really have an API authentication scheme. The "API" routes use the cookie-based authentication and the Django views require CSRF tokens, which is inconvenient …

Add an API route to trigger [re-]training of models (#124)

---

README.md
src/tram/renderers.py
src/tram/templates/index.html
src/tram/urls.py
src/tram/views.py
tests/tram/test_views.py

JSON exports were being rendered through an HTML template due to
content negotiation in the browser (e.g. Accept:text/html). This commit
forces the renderer to use JSON regardless of content negotiation and
also cleans up the json and docx export code.

Fix JSON export for reports (#175)

---

docker/docker-compose.yml

The docker-compose.yml file was missing the nginx image for tram. Without this image, the app won't start when you install it following the steps in the installation guide. With this change, the bug will be fixed.

modified nginx image on docker-compose.yml

---

Makefile
docker/docker-compose.yml

This Pull Request has been created because I found some errors installing TRAM container images with Docker Compose v2.
This error occurs when starting TRAM container images from the `start-container` task in Makefile.
For the error details, see the following:
```sh
$ make start-container
docker-compose -f docker/docker-compose.yml up -d
make: docker-compose: No such file or directory
make: *** [start-container] Error 1
```
It uses Docker Compose version v2.29.7 which is installed by Docker Desktop on Mac.
The recommended command-line syntax for Docker Compose v2 is `docker compose`.
https://docs.docker.com/compose/releases/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2
This Pull Request changes the compose command to replace `docker-compose` with `docker compose`. …

Update for Compatibility with Docker Compose v2
